chapter3課題完了
widesnow-t/furiPHP_exercise pull request #2
Opened 2021-09-15 19:21 UTC by widesnow-t

2021-09-15 19:24 UTC, widesnow-t commented
課題3完了しました､確認お願いします｡

2021-09-15 21:32 UTC, kazu-taka requested changes
@widesnow-t 
コメントしたので修正お願いします✨

2021-09-15 21:32 UTC, kazu-taka commented on chap3_1.php
> +}
@widesnow-t 
こちらのサイトを見ながらスペースの位置を確認お願いします✨
https://www.ritolab.com/entry/208

- `=`の前後にスペースを入れる
- `,`の後ろにスペースを入れる
- `(`の後ろにはスペースを入れない

```php
<?php 
$blood_types = ["A", "B", "O", "AB"];
foreach ($blood_types as $blood_type) {
    var_dump($blood_type ."型です");
}
```

2021-09-15 21:32 UTC, kazu-taka commented on chap3_2.php
> +
@widesnow-t 
こちらの空行は削除して下さい✨

2021-09-15 21:32 UTC, kazu-taka commented on chap3_2.php
> +    }
@widesnow-t 
forecahの中のインデントとifの中のインデントが半角スペース4文字になっていないので修正お願いします:bow:

2021-09-15 21:32 UTC, kazu-taka commented on chap3_3.php
> +	echo $start_number;
@widesnow-t 
こちらもインデントの修正をお願いします:bow:
また、演算子(`%`や`+`、`-`)の前後にもスペースを入れるようにして下さい👍

2021-09-15 21:35 UTC, kazu-taka commented
@widesnow-t 
プリリクエストが`main`←`chapter3`になるように修正して下さい🙏

2021-09-17 01:56 UTC, kazu-taka commented on chap3_2.php
> +}
@widesnow-t 
インデントの修正とifの後にスペースお願いします:bow:

2021-09-17 01:57 UTC, kazu-taka commented on chap3_3.php
> +echo $start_number;
@widesnow-t 
こちらもインデントの修正お願いします:bow:

2021-09-17 20:16 UTC, kazu-taka requested changes
@widesnow-t 
コメントしたので修正お願いします🙏
修正後Slackでご連絡下さい✨

2021-09-17 20:16 UTC, kazu-taka commented on chap3_2.php
> +}
@widesnow-t 
foreachの中のコードはインデントするようにお願いします🙏
```php
foreach(range(1, 100) as $int) {
    if ($int % 3 == 0) {
        echo "アホ";
    } else {
        echo $int; 
    }
}
```

2021-09-17 20:16 UTC, kazu-taka commented on chap3_3.php
> +}
@widesnow-t 
こちらもforeachの中はインデントするようにお願いします！
また、3や5の倍数のときも数字が表示されてしまうので、うまくelseを使用して表示されないように修正して下さい🙏

2021-09-18 08:48 UTC, kazu-taka requested changes
@widesnow-t 
コメントしたので修正お願いします🙏

2021-09-18 08:48 UTC, kazu-taka commented on chap3_2.php
> +    }
@widesnow-t 
基本的に弊社のカリキュラム通り(本も含む)、ifの中のコードはインデントして頂きたいので、修正お願いします🙏
他のの課題も同様に修正お願いします!!
公式ドキュメントも載せておきます！
https://www.php.net/manual/ja/control-structures.if.php

2021-09-18 08:48 UTC, kazu-taka commented on chap3_3.php
> +    echo $start_number;
@widesnow-t 
ifの最後の}がないので、}の追加とインデント修正お願いします！

2021-09-19 05:27 UTC, kazu-taka requested changes
@widesnow-t 
全てのインデントの修正お願いします:bow:

2021-09-19 05:27 UTC, kazu-taka commented on chap3_1.php
> +    }
@widesnow-t 
foreach自体はインデントせず、中をインデントするようにお願いします🙏
```php
$blood_types = ["A", "B", "O", "AB"];
foreach ($blood_types as $blood_type) {
    var_dump($blood_type ."型です");
}
```

2021-09-19 05:27 UTC, kazu-taka commented on chap3_2.php
> +    }
@widesnow-t 
こちらも課題1のforeachと同じように、if自体はインデントせず、中のコードだけインデントお願いします:bow:
昨日共有させて頂きましたマニュアルとカリキュラムと本のコードのインデントを確認しながらコーディングお願いします:bow:

2021-09-19 05:27 UTC, kazu-taka commented on chap3_3.php
> +    echo $start_number;
@widesnow-t 
インデントの修正お願いします:bow:

2021-09-19 23:12 UTC, kazu-taka requested changes
@widesnow-t 
インデントの修正お願いします:bow:

2021-09-19 23:12 UTC, kazu-taka commented on chap3_2.php
> +    }
@widesnow-t 
インデントの修正お願いします！
```php
if ($int % 3 == 0) {
    echo "アホ";
} else {
    echo $int; 
}
```

2021-09-19 23:12 UTC, kazu-taka commented on chap3_3.php
> +}
@widesnow-t 
インデントの修正お願いします！
```php
foreach (range(1, 100) as $start_number) {
    if ($start_number % 3 == 0 && $start_number % 5 == 0) {
        echo "FizzBuzz";
    } elseif ($start_number % 3 == 0) {
        echo "Fizz";
    } elseif ($start_number % 5 == 0) {
        echo "Buzz";
    } else {
        echo $start_number;
    }
}
```

2021-09-20 03:59 UTC, merged