Chapter1
widesnow-t/furiPHP_exercise pull request #5
Opened 2021-09-16 06:25 UTC by widesnow-t

2021-09-16 06:26 UTC, widesnow-t commented
課題①完了しました

2021-09-16 07:08 UTC, kazu-taka requested changes
@widesnow-t 
コメントしたので確認お願いします:bow:

2021-09-16 07:08 UTC, kazu-taka commented on chap1_1.php
> +$teacher =fgets(STDIN );
@widesnow-t 
`=`の後ろにもスペースお願いします！
`)`の前はスペース入れなくて良いです！
こちらのリンク(コーディング規約)を参考に、どこにスペースを入れるべきか確認お願いします:bow:
https://www.ritolab.com/entry/208

2021-09-16 07:08 UTC, kazu-taka commented on chap1_1.php
> +$teacher =fgets(STDIN );
他の=や)の部分も全て見直しお願いします:bow:

2021-09-16 07:08 UTC, kazu-taka commented on chap1_2.php
> +var_dump("面積は" . ($top+$bottom)*$height/2 );
@widesnow-t 
演算子(+や*)の前後もスペースお願いします！

2021-09-16 20:36 UTC, kazu-taka commented on chap1_2.php
> +$top=fgets (STDIN);
@widesnow-t 
こちらの`=`の前後にもスペースお願いします:bow:

2021-09-16 20:37 UTC, kazu-taka commented on chap1_1.php
> +?>
@widesnow-t 
PHPのプログラムの下にHTML等がない場合は、`?>`は書かない方がいいので、全ての課題の閉じタグを削除お願いします:bow:
https://thesaibase.com/end-tag/

2021-09-17 20:09 UTC, kazu-taka commented on chap1_2.php
> +$top=fgets (STDIN);
@widesnow-t 
こちらの修正が終わっていないようなので確認お願いします:bow:
https://github.com/widesnow-t/furiPHP_exercise/pull/5/files#r710456324

2021-09-17 20:09 UTC, kazu-taka approved these changes
@widesnow-t 
1箇所修正して頂いたらマージしてOKです👍

2021-09-18 09:46 UTC, merged