php1challenge課題２
widesnow-t/furiPHP_exercise pull request #7
Opened 2022-01-03 23:55 UTC by widesnow-t

### カリキュラムURL
https://github.com/elites-team/2months_course/blob/master/doc/06_php/exercise/07.md
### 課題番号

チャレンジ課題2
### 現在の状況
game.phpのfightの下の部分がcssがうまく行かない

### 期待していた動作
fightの下の部分がカリキュラムどうりにならない

### 調べたこと・参考にしたURL
display flexについて
https://webdesign-trends.net/entry/8148

2022-01-04 04:28 UTC, kazu-taka commented
@widesnow-t 
明日からサービス再開なので確認させて頂きますが、具体的に分かるようにスクリーンショットの添付をおねがいします🙏

2022-01-04 06:16 UTC, kazu-taka commented on game/game.php
> +                        <li class="attack"><?= "攻撃技は？" ?></li>
@widesnow-t 
他の場所でもliタグを使っているところがありますが、liタグは何かのリストを表現する際に使用するので、divやpタグを使用するのが良いと思います✨
複雑なデザインはgrid-template-areasを使用すると実現する事が可能です😊
https://developer.mozilla.org/ja/docs/Web/CSS/grid-template-areas

2022-01-04 21:24 UTC, widesnow-t commented on game/game.php
> +                        <li class="attack"><?= "攻撃技は？" ?></li>
![スクリーンショット 2022-01-05 6 20 05（2）](https://user-images.githubusercontent.com/89765385/148125395-303842ca-8e24-4ef7-9ddf-7850ac0cb359.png)
最後の文字が、のびないです、よろしくお願いします、

2022-01-04 21:37 UTC, widesnow-t commented on game/game.php
> +                        <li class="attack"><?= "攻撃技は？" ?></li>
解決しました、-marginでうまく出ました！

2022-01-05 03:36 UTC, kazu-taka requested changes
@widesnow-t 
ワーニングが出ているので、ワーニングが出ないように修正お願いします✨
![image](https://user-images.githubusercontent.com/5278718/148156694-048e54fb-30c8-443d-b966-2763a5a00617.png)

こちらのデザインが、カリキュラムと違うので、修正お願いします🙏
![image](https://user-images.githubusercontent.com/5278718/148156738-ae620c34-5d4d-473e-86ff-7e51b87da3ea.png)

2022-01-05 03:36 UTC, kazu-taka commented on game/css/style.css
> +.bu {
@widesnow-t 
buというclass名だと分かりにくいの、別名に修正お願いします🙏

2022-01-05 03:36 UTC, kazu-taka commented on game/css/style.css
> +.bu {
@widesnow-t 
paddingを指定していないため、入力中の点滅カーソルが左側に寄って見えなくなってしまっています✨
![image](https://user-images.githubusercontent.com/5278718/148156574-eb366215-c57d-4d01-9849-ae5d46e3074f.png)

【paddingを指定した場合】
![image](https://user-images.githubusercontent.com/5278718/148156595-55ab6259-3c61-44e3-a39b-215df8884ca9.png)

2022-01-05 08:29 UTC, widesnow-t commented on game/css/style.css
> +.bu {
修正しました、確認お願いします。
warningは値が入ってないってことですかね、まだ理解が足りて無いです。

2022-01-05 12:46 UTC, kazu-taka commented
@widesnow-t 
名前と攻撃内容、攻撃技は？と攻撃ボタンの間が空きすぎているので、もう少し真ん中に寄せるようにお願いします✨
![image](https://user-images.githubusercontent.com/5278718/148219081-bf0c3099-7846-4519-bcf6-0c5edb3f0db1.png)

<br>

4つの変数が初期化されていないので、警告メッセージが表示されています^^;
isset関数を使って警告がでないようにしてみて下さい✨
https://hacknote.jp/archives/21606/


![image](https://user-images.githubusercontent.com/5278718/148219299-29094393-ef2e-4c96-a7e2-62c2423d12cb.png)

![image](https://user-images.githubusercontent.com/5278718/148219483-9b6022cf-071f-4644-a558-c32fe1ade04c.png)

<br>

スタートへ戻るの文字が上に寄っているので修正お願いします🙏
![image](https://user-images.githubusercontent.com/5278718/148219450-6a313b6a-d310-4d80-bbb4-290494257e6a.png)

2022-01-07 03:08 UTC, zeeero4 commented on game/css/style.css
> +        /200px 100px 100px;
ここの部分もう少し真ん中に寄せるようにお願いします
https://github.com/widesnow-t/furiPHP_exercise/pull/7#issuecomment-1005656447

課題の実行結果は以下のような画像ですので､もう少し近づけてみてください😊
![スクリーンショット 2022-01-07 10 42 43](https://user-images.githubusercontent.com/68971142/148477839-e8266995-3af9-41f2-beff-cfefa5ea9572.png)

2022-01-07 03:08 UTC, kzri4 commented on game/game.php
> +                <?= h($message) ?>
修正頂いた内容だと､攻撃に進むと画像のようにエラー文が表示されてしまいますので､どこが原因なのか考えてみてください😊

![スクリーンショット 2022-01-07 11 33 53](https://user-images.githubusercontent.com/68971142/148485085-5ec270a5-320e-445b-bea9-48e8c0740362.png)

2022-01-07 04:52 UTC, widesnow-t commented on game/game.php
> +                <?= h($message) ?>
タグがないので、nullになるですかね？
変更しました、確認お願いします。

2022-01-07 05:58 UTC, kzri4 commented on game/game.php
> -    $messages = filter_input(INPUT_POST, 'messages');
`filter_input`は残すようにお願いします! でなければ､ 以下のエラーが出てしまいます!

```
Warning: Undefined variable $message in /var/www/html/game/game.php on line 116
```

2022-01-07 05:58 UTC, kzri4 commented on game/game.php
> +                <p><?= h($message) ?></p>
タグをつけたのも正解ですが､根本的な理由は `h()`がついていることになります😊

`$message`には`$attack === 0`の場合に攻撃に失敗､ `$attack >= 2000`のが場合にクリティカルヒットの文字列が入りますが､一方で､`$attack`が1〜1999の場合は`$message`がnullになります｡
そのため､`nul`lの状態の変数に`h()`関数を使用してしまうことで､画像のエラーが発生という仕組みになります｡

ですので､ `<p><?= h($message) ?></p`>  =>  `<p><?= $message ?></p>` とすることでエラーは発生しなくなります!

そもそも､`htmlspecialchars`はHTMLの特殊タグをエスケープするためのものなので､今回のように､予め代入される予定の文字列を自分で決めておいて､HTMLの特殊タグが入ることのない場合は､htmlspecialcharsを使用する必要はありません｡
よって､`<p><?= $message ?></p>`で問題ないということになります😊

https://qiita.com/mpyw/items/19e6fed835ccdbcb0d6d
https://qiita.com/pito555/items/a2f649a050a0b7a46cf1

2022-01-07 05:58 UTC, kzri4 commented on game/game.php
> +                <p><?= h($messages) ?></p>
ここも上記同様です😊

2022-01-07 10:17 UTC, widesnow-t commented on game/game.php
> +                <p><?= h($message) ?></p>
なるほどです！
エラーメッセージにhtmlspecialcharsが入ってる時点で、疑ば良かったのですね！
まさかhとは、ありがとうございます。

2022-01-07 11:48 UTC, merged